name: cuca-build
on: [push]
jobs:
  flutter-build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter doctor
